=== jskopek/interoperability-data-model/common-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": [
    "IDMVersion",
    "1.2 2025-08-10",
    "license (c) EMerge Alliance 2025, Licensed CC BY-NC-ND 4.0 -All Rights Reserved",
    "This is the JSON schema for all IDM products.  Listed below are all the parameters that are common to all types of product",
    "Particular types of product have their own schemas defined in separate files, which must be in the same folder, or sub-folders.",
    
    "fileVersion: 1.01","fileDate 2025-09-26"
  ],
  "type": "object",
  "properties": {
    "IDMVersion": { "const": "1.2 2025-08-10" },
    "license": { "const": "(c) EMerge Alliance 2025, Licensed CC BY-NC-ND 4.0 -All Rights Reserved" },
    "productName": { "$ref": "productName-schema.json#/schema" },
    "productIdentifier": { "$ref": "productIdentifier-schema.json#/schema" },
    "typeSpecificParameters": { "$ref": "typeSpecifics-schema.json#/schema" },
    "environmental": { "icon": "cloud-sun", "$ref": "environmental-schema.json#/schema" },
    "manufacturer": { "icon": "building", "$ref": "manufacturer-schema.json#/schema" },
    "productSeries": { "icon": "boxes-stacked", "$ref": "productSeries-schema.json#/schema" },
    "datasheetHyperlink": {
      "type": "string",
      "description":"This should hyperlink to a web page or PDf that is specific to this product.  (If there isn't one, leave blank.)",
      "format": "uri"
    },
    "description": {
      "title":"Product description",
      "type": "string",
      "description":"This is for a free-text description of the product. It should consist only of text, but may be up to 64kbytes long.",
      "format": "textarea",
      "minLength": 0,
      "maxLength": 65535
    },
    "distributors": { "icon": "truck", "$ref": "distributors-schema.json#/schema" },
    "systemsIntegrators": { "icon": "handshake", "$ref": "distributors-schema.json#/schema" },
    "embargoedCountries": { "icon": "ban", "$ref": "embargoedCountries-schema.json#/schema" },
    "notRecommendedForNewDesigns": { "type": "boolean" },
    "listingAuthorities": { "icon": "certificate", "$ref": "listingAuthorities-schema.json#/schema" },
    "productWarrantyYrs": { "type": "number" },
    "files": { "icon": "folder-open", "$ref": "files-schema.json#/schema" },
    "images": { "icon": "images", "$ref": "images-schema.json#/schema" },
    "listPriceUSD": { "type": "number" },
    "fileVersion":{"type":"string", "default":"0.0"},
    "fileDate":{"type":"string", "format": "date"},
    "changeRecord":{"icon": "clock-rotate-left", "$ref": "changeRecord-schema.json#/schema"}
  },
  "required": [
    "IDMVersion",
    "license",
    "manufacturer",
    "productIdentifier"
  ],
  "selectionTool": {
    "$comment": "The selection tool will provide the filter, display and comparison sections with the values of those parameters listed in each of the referenced files",
    "filter": [
      "manufacturer.json",
      "productSeries.json",
      "notRecommendedForNewDesigns.json",
      "typeSpecificParameters.json",
      "environmental.json"
    ],
    "display": [
      "productIdentifier.json",
      "images.json",
      "typeSpecificParameters.json",
      "environmental.json",
      "files.json"
    ],
    "comparison": [
      "productIdentifier.json",
      "typeSpecificParameters.json",
      "environmental.json"
    ]
  }
}

=== jskopek/interoperability-data-model/testEVcharger.json
{
  "$schema": "common-schema.json",
  "IDMVersion": "1.2 2025-08-10",
  "license": "(c) EMerge Alliance 2025, Licensed CC BY-NC-ND 4.0 -All Rights Reserved",
  "productName": "60kW DC-DC Mobile EV Charger",
  "fileVersion": "0.0",
  "fileDate": "2026-06-09",
  "productIdentifier": "AMP-8002-60",
  "datasheetHyperlink": "https://www.ampernext.com/products/60kw-mobile-dc-dc-ev-charger-dc-input/",
  "description": "This data is taken from https://dcide.app/products/60kw-dc-dc-mobile-ev-charger-amp-8002-60-dc-dc-mobile-ev-charger-676d68cdc8a1498c3e181318#electrical\n",
  "typeSpecificParameters": {
    "converter": {
      "port1": {
        "portName": "Input",
        "frequency": "DC",
        "connectionType": "DC",
        "SOA": {
          "maxVoltage": {
            "value": 820,
            "units": "V"
          },
          "minVoltage": {
            "value": 300,
            "units": "V"
          },
          "maxCurrentIn": {
            "value": 100,
            "units": "A"
          },
          "maxPowerIn": {
            "value": 60,
            "units": "kW"
          },
          "maxVoltageToGround": {
            "value": 1000,
            "units": "V"
          }
        },
        "VIrelationship": {
          "portType": "constantPower"
        },
        "poleLocallyGrounded": "Float",
        "groundWire": "required",
        "connector": {
          "connectionType": "bolt",
          "bolt": "M8 (5/16\")"
        },
        "prechargeProtection": "neither"
      },
      "port2": {
        "portName": "Output",
        "frequency": "DC",
        "connectionType": "DC",
        "VIrelationship": {
          "portType": "batteryChargingPort",
          "chargeCharacteristics": {
            "portType": "batteryCharging",
            "minNominalBattVolts": {
              "value": 150,
              "units": "V"
            },
            "maxNominalBattVolts": {
              "value": 1000,
              "units": "V"
            },
            "maxChargingCurrent": {
              "value": 100,
              "units": "A"
            },
            "outputPowerLimit": {
              "value": 60,
              "units": "kW"
            },
            "chemistry": "Lithium-ion",
            "BMScommunication": {
              "protocol": [
                "ModBus TCP"
              ]
            }
          }
        },
        "poleLocallyGrounded": "Float",
        "groundWire": "offered",
        "connector": {
          "connectionType": "plugAndSocket",
          "type": "CCS1, CCS2, NACS, Chademo",
          "gender": "Free socket"
        }
      },
      "galvanicSeparation": true,
      "transferPowerSetBy": "BMS",
      "mechanical": {
        "size": {
          "units": "mm",
          "length": 870,
          "width": 670,
          "height": 480
        },
        "weight": {
          "value": 100,
          "units": "kg"
        },
        "mountingType": [
          "Free-standing"
        ]
      }
    }
  },
  "environmental": {
    "operatingTemperature": {
      "min": -25,
      "max": 55,
      "unit": "°C"
    },
    "operatingHumidity": {
      "max": 95
    },
    "ingressProtection_IP": "IP54"
  },
  "manufacturer": {
    "coName": "AmperneXt",
    "webHomePageURL": "www.ampernext.com"
  }
}

=== jskopek/interoperability-data-model/testCable.json
{
  "IDMVersion": "1.2 2025-08-10",
  "license": "(c) EMerge Alliance 2025, Licensed CC BY-NC-ND 4.0 -All Rights Reserved",
  "fileVersion": "0.0",
  "fileDate": "2026-06-09",
  "$schema": "common-schema.json",
  "productIdentifier": "REC20FT10PR-UK",
  "productName": "Solar panel extension cable pair",
  "description": "The Renogy Male to Female Solar Extension Cable allows you to make spatial adjustments to your solar power system in one simple step. This extension cable runs between the solar panel and charge controller or between two solar panels; allowing for greater space between both items. Like all other Solar Extension Cables; this product allows for greater customization of the solar power system.\n",
  "productSeries": "Extension Cables",
  "datasheetHyperlink": "https://uk.renogy.com/collections/extension-cables-1/products/male-to-female-solar-extension-cable-a-pair",
  "typeSpecificParameters": {
    "cable": {
      "ratedVoltage": {
        "value": 1000,
        "units": "V"
      },
      "gndVoltage": {
        "value": 1000,
        "units": "V"
      },
      "numberOfConductors": 2,
      "length": {
        "value": 10,
        "units": "ft"
      },
      "conductorSize": "10AWG, 6.0mm²",
      "conductorMaterial": "copper",
      "sheathColor": "Black",
      "conA": {
        "connectionType": "plugAndSocket",
        "type": "MC4",
        "gender": "plugPositive"
      },
      "conB": {
        "connectionType": "plugAndSocket",
        "type": "MC4",
        "gender": "plugNegative"
      }
    }
  },
  "manufacturer": {
    "coName": "Renogy",
    "webHomePageURL": "uk.renogy.com"
  },
  "environmental": {
    "operatingTemperature": {
      "min": -40,
      "max": 185,
      "unit": "°C"
    },
    "ingressProtection_IP": "IP65"
  },
  "listingAuthorities": [
    {
      "LAName": "TUV"
    }
  ]
}

=== jskopek/interoperability-data-model/testContactor.json
{
  "IDMVersion": "1.2 2025-08-10",
  "license": "(c) EMerge Alliance 2025, Licensed CC BY-NC-ND 4.0 -All Rights Reserved",
  "productName": "Hybrid high voltage relay",
  "fileVersion": "0.0",
  "fileDate": "2026-06-09",
  "productIdentifier": "HVR10-N0C1G1-BS02D9-300A",
  "productSeries": "HVR10",
  "datasheetHyperlink": "https://dcide-payload-nyc.nyc3.digitaloceanspaces.com/dcide-production/d-hvr10-en-EZZWZj.pdf",
  "description": "The HVR10 is a hybrid powerful high voltage relay in a compact design. It combines physical isolation of an electro-mechanical contact and state-of-the-art semi-conductor technology. The hybrid, arc-free switching system allows repeated and reliable disconnection, even in the event of an overload, of up to 2 megawatts – 2,000 A/1,000 V. The HVR10 withstands high short circuit currents up to 5,000 A until the fast HV-fuse trips. The compact unit can switch and permanently process 300 A up to 50,000 times, arc-free and wear-free. The innovative self-monitoring function immediately signals critical operating conditions to the controlgear.\",\n  \"manufacturer",
  "typeSpecificParameters": {
    "contactor": {
      "coilACDC": "DC",
      "minDCVolts": {
        "value": 12,
        "units": "V"
      },
      "coilContactIsolationVolts": {
        "value": 4000,
        "units": "V"
      },
      "contactRating": {
        "maxVoltageDC": {
          "value": 900,
          "units": "V"
        },
        "maxSteadyCurrent": {
          "value": 250,
          "units": "A"
        },
        "ampsBreakingCapacity": {
          "value": 2,
          "units": "kA"
        },
        "AEndConnection": {
          "connectionType": "bolt",
          "bolt": "M10 (13/32\")"
        },
        "BEndConnection": {
          "connectionType": "bolt",
          "bolt": "M10 (13/32\")"
        }
      },
      "numberOfPolesNormallyOpen": 1,
      "numberOfPolesNormallyClosed": 0,
      "numberOfPolesChangeover": 0,
      "numberOfPolesMakeBeforeBreak": 0,
      "mechanical": {
        "size": {
          "units": "mm",
          "width": 80,
          "depth": 90,
          "height": 87
        },
        "weight": {
          "value": 550,
          "units": "g"
        },
        "mountingType": [
          "Panel mount"
        ]
      }
    }
  },
  "environmental": {
    "operatingTemperature": {
      "min": -40,
      "max": 85,
      "unit": "°C"
    },
    "operatingHumidity": {
      "max": 85
    }
  },
  "manufacturer": {
    "coName": "E-T-A Elektrotechnische Apparate GmbH",
    "webHomePageURL": "www.e-t-a.co.uk"
  },
  "listingAuthorities": [
    {
      "LAName": "KBA"
    }
  ]
}

=== jskopek/interoperability-data-model/testGenerator.json
{
  "$schema": "common-schema.json",
  "IDMVersion": "1.2 2025-08-10",
  "license": "(c) EMerge Alliance 2025, Licensed CC BY-NC-ND 4.0 -All Rights Reserved",
  "productName": "SIP 03920 Portable Generator",
  "productIdentifier": "12867",
  "typeSpecificParameters": {
    "nonRenewableSource": {
      "outputPort": {
        "portName": "Mains out",
        "frequency": "P50",
        "connectionType": "P1S",
        "VIrelationship": {
          "portType": "constantVoltage",
          "openCctVolts": {
            "value": 230,
            "units": "Vrms"
          }
        },
        "poleLocallyGrounded": "Float",
        "groundWire": "neither",
        "connector": {
          "connectionType": "plugAndSocket",
          "type": "BS.1363",
          "gender": "Socket"
        }
      },
      "alternativeOutput": {
        "portName": "12V DC",
        "frequency": "DC",
        "connectionType": "DC",
        "VIrelationship": {
          "portType": "constantVoltage",
          "openCctVolts": {
            "value": 12,
            "units": "V"
          }
        },
        "poleLocallyGrounded": "Float",
        "groundWire": "neither",
        "connector": {
          "connectionType": "plugAndSocket",
          "type": "Cigar lighter",
          "gender": "Socket"
        }
      },
      "mechanical": {
        "size": {
          "units": "cm",
          "length": 65,
          "width": 45,
          "height": 45
        },
        "weight": {
          "value": 21,
          "units": "kg"
        },
        "mountingType": [
          "Free-standing"
        ]
      }
    }
  },
  "environmental": {
    "operatingTemperature": {
      "min": 0,
      "max": 50,
      "unit": "°C"
    },
    "ingressProtection_IP": "IP21",
    "coolingMethod": "passive",
    "RoHScompliant": true
  },
  "manufacturer": {
    "coName": "Draper",
    "webHomePageURL": "drapertools.com"
  },
  "productSeries": "Inverter generators",
  "datasheetHyperlink": "https://www.drapertools.com/product/95176/petrol-inverter-generator-700w/",
  "description": "This is just a randomly chosen petrol generator.",
  "notRecommendedForNewDesigns": false,
  "listingAuthorities": [
    {
      "LAName": "UL",
      "standard": "248-14 File E33925"
    }
  ],
  "productWarrantyYrs": 1,
  "fileVersion": "1.0",
  "fileDate": "2026-06-03",
  "changeRecord": [
    {
      "date": "2026-06-03",
      "version": "1.1",
      "author": "Chris Moller",
      "note": "Just a test to see if I can create a new test file."
    }
  ]
}

=== jskopek/interoperability-data-model/testInverter.json
{
  "$schema": "common-schema.json",
  "IDMVersion": "1.2 2025-08-10",
  "license": "(c) EMerge Alliance 2025, Licensed CC BY-NC-ND 4.0 -All Rights Reserved",
  "productName": "Sunshine Solar 3kW Inverter",
  "fileVersion": "0.0",
  "fileDate": "2026-06-10",
  "productIdentifier": "VP3000-48V",
  "productSeries": "Solar inverters",
  "datasheetHyperlink": "https://www.sunshinesolar.co.uk/media/ecom/prodpdf/VP3000.pdf",
  "description": "With a robust 3000W continuous output, the VP3000 is capable of running multiple devices simultaneously, including kitchen appliances, power tools, entertainment systems, and charging equipment. Its pure sine wave output ensures compatibility with delicate electronics such as laptops, medical devices, TVs, and modern charging systems, reducing the risk of interference or damage. \n\nEngineered for reliability, the inverter features advanced protection mechanisms including overload, over-temperature, short-circuit, and low/high voltage safeguards. These built-in protections help maintain safe operation and extend the lifespan of both the inverter and your connected devices. \n\nThe Sunshine VP3000 is designed with efficiency and durability in mind, making it suitable for both mobile and stationary installations. Whether you're upgrading your off-grid setup, powering a mobile workspace, or ensuring dependable backup power, this inverter provides consistent performance when you need it most.\n\n\nKEY FEATURES\n\n3000W continuous output with high surge capacity \nPure sine wave technology for clean, stable power \n12V DC to 230V AC conversion\nSuitable for RVs, caravans, boats & off-grid systems \nSupports sensitive electronics and high-demand appliances \nBuilt-in protection: overload, short circuit, temperature & voltage safeguards \nEfficient, reliable and designed for long-term use .\nSoft Start\nRCD Compatibility - Switchable\nDual AC outlets\nUSB output 5VDC - 2.1A\n*Optional Extra - Remote On/Off Switch*",
  "typeSpecificParameters": {
    "converter": {
      "port1": {
        "portName": "Input",
        "frequency": "DC",
        "SOA": {
          "maxVoltage": {
            "value": 62,
            "units": "V"
          },
          "nomVoltage": {
            "value": 48,
            "units": "V"
          },
          "minVoltage": {
            "value": 43.2,
            "units": "V"
          },
          "maxCurrentIn": {
            "value": 75,
            "units": "A"
          }
        },
        "VIrelationship": {
          "portType": "constantPower"
        },
        "connector": {
          "connectionType": "other",
          "other": "4 x 700mm - 16mm²"
        }
      },
      "port2": {
        "portName": "Output",
        "frequency": "P50",
        "connectionType": "P1S",
        "SOA": {
          "nomVoltage": {
            "value": 240,
            "units": "Vrms"
          },
          "maxPowerOut": {
            "value": 3000,
            "units": "W"
          }
        },
        "VIrelationship": {
          "portType": "constantVoltage",
          "openCctVolts": {
            "value": 240,
            "units": "V"
          }
        },
        "groundWire": "offered",
        "connector": {
          "connectionType": "plugAndSocket",
          "type": "BS.1363",
          "gender": "Socket"
        }
      },
      "transferPowerSetBy": "port2",
      "staticPower": {
        "value": 12,
        "units": "W"
      },
      "transferEfficicency%P1toP2": 90,
      "shortOverload": {
        "peakPower": {
          "value": 4500,
          "units": "W"
        },
        "maxDuration": {
          "value": 10,
          "units": "s"
        }
      },
      "mechanical": {
        "size": {
          "units": "mm",
          "length": 402,
          "width": 220,
          "height": 150
        },
        "weight": {
          "value": 7.95,
          "units": "kg"
        }
      }
    }
  },
  "environmental": {
    "operatingTemperature": {
      "min": -10,
      "max": 50,
      "unit": "°C"
    },
    "operatingHumidity": {
      "min": 20,
      "max": 90
    }
  },
  "manufacturer": {
    "coName": "Sunshine Solar",
    "webHomePageURL": "www.sunshinesolar.co.uk"
  },
  "listingAuthorities": [
    {
      "LAName": "Cenelec",
      "standard": "EN61000-3-2-3, EN55022, EN55024,"
    },
    {
      "LAName": "IEC",
      "standard": "62040-1:2008"
    }
  ]
}
